services:
  shodan-proxy:
    image: liuweitao/shodan-proxy:latest
    container_name: shodan-proxy
    volumes:
      - ./config:/app/config
    restart: unless-stopped
    ports:
      - "8080:8080"
